# DATABASE
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# TOYYIBPAY
payment.gateway.userSecretKey=${TOYYIBPAY_SECRET_KEY}
payment.gateway.categoryCode=${TOYYIBPAY_CATEGORY_CODE}

# EMAIL
spring.mail.password=${EMAIL_PASSWORD}

# API KEYS
geocoding.api.key=${GEOCODING_API_KEY}